name: Update a resource in KG-Registry
description: Request an update to a resource in the registry
title: Update this resource - [Name Here]
labels: [ Update ]

body:
  - type: markdown
    attributes:
      value: This is the form for requesting an update to a resource in KG-Registry.
  - type: input
    id: name
    attributes:
      label: Name
      description: What is the name of this resource?
      placeholder: e.g., KG-Tofu
    validations:
      required: true
  - type: input
    id: update
    attributes:
      label: Update
      description: What should be updated in the resource?
      placeholder: e.g., remove homepage link
    validations:
      required: true
  - type: input
    id: contributor_name
    attributes:
      label: Contributor Name
      description: What is your name? This will be used for attribution.
      placeholder: e.g., Tabatha Butterscotch
    validations:
      required: true
  - type: input
    id: contributor_github
    attributes:
      label: Contributor GitHub
      description: What is your GitHub name, without the @ symbol?
      placeholder: e.g., tbuttersco
    validations:
      required: true
  - type: input
    id: contributor_orcid
    attributes:
      label: Contributor ORCID
      description: What is your ORCID iD?
      placeholder: e.g., 0000-0001-2345-6789
    validations:
      required: false