#!/usr/bin/env python3
"""Convert the KG-Registry YAML metadata to Turtle (RDF) format.

Usage:
    python util/yaml2ttl.py <input.yml> <output.ttl>

The script reads the YAML file generated by `sort-resources.py` and creates an RDF graph
using `rdflib`. For each resource entry it creates a URI based on its `id`
and maps a comprehensive set of properties to RDF predicates using standard namespaces.

Properties mapped include:
    - id (dcterms:identifier)
    - name (rdfs:label, schema:name)
    - description (dcterms:description)
    - homepage_url (foaf:homepage, schema:url)
    - repository (doap:repository)
    - license (dcterms:license)
    - version (dcterms:hasVersion)
    - language (dcterms:language)
    - activity_status (adms:status)
    - domains, tags, taxon (multiple)
    - contacts, curators, funding, publications, usages (complex properties)

The generated Turtle file is written to the specified output path.
"""

import sys
import yaml
from argparse import ArgumentParser
from urllib.parse import quote

from rdflib import Graph, URIRef, Literal, Namespace
from rdflib.namespace import RDF, RDFS, DCTERMS, OWL, XSD

# Define namespace URIs
KGREGISTRY_BASE = "http://purl.obolibrary.org/obo/"
SCHEMA = Namespace("http://schema.org/")
FOAF = Namespace("http://xmlns.com/foaf/0.1/")
DOAP = Namespace("http://usefulinc.com/ns/doap#")
SKOS = Namespace("http://www.w3.org/2004/02/skos/core#")
ADMS = Namespace("http://www.w3.org/ns/adms#")


def serialize_literal(value):
    """Convert a Python value to an RDF Literal with appropriate type."""
    if isinstance(value, bool):
        return Literal(value, datatype=XSD.boolean)
    elif isinstance(value, int):
        return Literal(value, datatype=XSD.integer)
    elif isinstance(value, float):
        return Literal(value, datatype=XSD.float)
    else:
        return Literal(str(value))


def add_string_property(graph, subject, predicate, value):
    """Add a string property to the graph if value is not None."""
    if value:
        graph.add((subject, predicate, Literal(str(value))))


def add_uri_property(graph, subject, predicate, value):
    """Add a URI property to the graph if value is not None."""
    if value:
        graph.add((subject, predicate, URIRef(str(value))))


def add_resource_to_graph(graph, resource):
    """Add a single resource and all its properties to the RDF graph."""
    resource_id = resource.get("id")
    if not resource_id:
        return

    uri = URIRef(KGREGISTRY_BASE + quote(resource_id, safe=""))

    # Core properties using standard RDF predicates
    add_string_property(graph, uri, DCTERMS.identifier, resource_id)
    add_string_property(graph, uri, RDFS.label, resource.get("name") or resource_id)
    add_string_property(graph, uri, SCHEMA.name, resource.get("name"))
    add_string_property(graph, uri, DCTERMS.description, resource.get("description"))
    add_uri_property(graph, uri, FOAF.homepage, resource.get("homepage_url"))
    add_uri_property(graph, uri, DOAP.repository, resource.get("repository"))
    add_string_property(graph, uri, DCTERMS.hasVersion, resource.get("version"))
    add_string_property(graph, uri, DCTERMS.language, resource.get("language"))

    # Activity status
    if resource.get("activity_status"):
        status_map = {
            "active": "Active",
            "inactive": "Inactive",
            "orphaned": "Orphaned",
        }
        status = status_map.get(resource.get("activity_status"), resource.get("activity_status"))
        graph.add((uri, ADMS.status, Literal(status)))

    # License
    license_obj = resource.get("license")
    if license_obj:
        if isinstance(license_obj, dict):
            if license_obj.get("id"):
                add_uri_property(graph, uri, DCTERMS.license, license_obj.get("id"))
            elif license_obj.get("label"):
                add_string_property(graph, uri, DCTERMS.license, license_obj.get("label"))
        else:
            add_uri_property(graph, uri, DCTERMS.license, license_obj)

    # Category (equivalent to rdf:type)
    category = resource.get("category")
    if category:
        graph.add((uri, RDF.type, URIRef(SCHEMA + category)))

    # Multi-valued properties: domains
    for domain in resource.get("domains", []):
        graph.add((uri, SKOS.inScheme, Literal(domain)))

    # Multi-valued properties: tags
    for tag in resource.get("tags", []):
        graph.add((uri, SKOS.related, Literal(tag)))

    # Multi-valued properties: taxa
    for taxon in resource.get("taxon", []):
        graph.add((uri, SCHEMA.about, URIRef(taxon)))

    # Multi-valued properties: synonyms
    for synonym in resource.get("synonyms", []):
        graph.add((uri, SKOS.altLabel, Literal(synonym)))

    # Date properties
    if resource.get("creation_date"):
        graph.add((uri, DCTERMS.created, Literal(resource.get("creation_date"), datatype=XSD.dateTime)))
    if resource.get("last_modified_date"):
        graph.add((uri, DCTERMS.modified, Literal(resource.get("last_modified_date"), datatype=XSD.dateTime)))

    # Infores ID
    if resource.get("infores_id"):
        add_string_property(graph, uri, SCHEMA.identifier, resource.get("infores_id"))

    # FAIRsharing ID
    if resource.get("fairsharing_id"):
        add_string_property(graph, uri, SKOS.notation, resource.get("fairsharing_id"))

    # Contacts (nested objects)
    for contact in resource.get("contacts", []):
        if isinstance(contact, dict):
            contact_id = contact.get("id")
            if contact_id:
                contact_uri = URIRef(KGREGISTRY_BASE + quote(contact_id, safe=""))
                graph.add((uri, FOAF.maker, contact_uri))
                add_string_property(graph, contact_uri, RDFS.label, contact.get("label"))
                add_string_property(graph, contact_uri, RDF.type, contact.get("category", "Agent"))

    # Curators (nested objects)
    for curator in resource.get("curators", []):
        if isinstance(curator, dict):
            curator_id = curator.get("id")
            if curator_id:
                curator_uri = URIRef(KGREGISTRY_BASE + quote(curator_id, safe=""))
                graph.add((uri, FOAF.workflowManager, curator_uri))
                add_string_property(graph, curator_uri, RDFS.label, curator.get("label"))

    # Funding sources (nested objects)
    for fund in resource.get("funding", []):
        if isinstance(fund, dict):
            org = fund.get("organization")
            if org:
                add_string_property(graph, uri, SCHEMA.funder, org)

    # Publications (nested objects)
    for pub in resource.get("publications", []):
        if isinstance(pub, dict):
            if pub.get("id"):
                graph.add((uri, DCTERMS.isReferencedBy, URIRef(pub.get("id"))))

    # Products (complex nested objects)
    for product in resource.get("products", []):
        if isinstance(product, dict):
            product_id = product.get("id")
            if product_id:
                product_uri = URIRef(KGREGISTRY_BASE + quote(product_id, safe=""))
                graph.add((uri, SCHEMA.hasPart, product_uri))
                add_string_property(graph, product_uri, RDFS.label, product.get("name"))
                add_string_property(graph, product_uri, DCTERMS.description, product.get("description"))
                add_uri_property(graph, product_uri, SCHEMA.url, product.get("product_url"))
                if product.get("category"):
                    graph.add((product_uri, RDF.type, URIRef(SCHEMA + product.get("category"))))


def main(argv):
    parser = ArgumentParser(description="Convert KG-Registry YAML to Turtle RDF")
    parser.add_argument("yaml_file", help="Input YAML file (registry/kgs.yml)")
    parser.add_argument("ttl_file", help="Output Turtle file")
    args = parser.parse_args(argv[1:])

    # Load YAML data
    with open(args.yaml_file, "r") as f:
        data = yaml.load(f, Loader=yaml.SafeLoader)

    g = Graph()

    # Bind namespace prefixes for readability
    g.bind("obo", Namespace(KGREGISTRY_BASE))
    g.bind("dcterms", DCTERMS)
    g.bind("rdfs", RDFS)
    g.bind("owl", OWL)
    g.bind("schema", SCHEMA)
    g.bind("foaf", FOAF)
    g.bind("doap", DOAP)
    g.bind("skos", SKOS)
    g.bind("adms", ADMS)

    # Process each resource
    for resource in data.get("resources", []):
        add_resource_to_graph(g, resource)

    # Serialize to Turtle
    g.serialize(destination=args.ttl_file, format="turtle")


if __name__ == "__main__":
    main(sys.argv)
