name: Build derived files
on:
  # Allows for on-demand build
  workflow_dispatch:
  # Automatically rebuilds when somebody edits a markdown file in
  # the kgmetadata/ directory
  push:
    branches:
      - main
    paths:
      - 'kgmetadata/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.2.30
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Create local changes
        run: |
          poetry install --no-interaction
          make
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "🚀 Automatically rebuilt derived files" -a
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update KG-Registry metadata
          title: 'Update KG-Registry metadata'
          body: |
            Recreates all KG-Registry metadata.