name: Build derived files
on:
  # Allows for on-demand build
  workflow_dispatch:
  # Automatically rebuilds when somebody edits a markdown file in
  # the resource/ directory
  push:
    branches:
      - main
    paths:
      - 'resource/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.5.4
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      - name: Create local changes
        run: |
          poetry install --no-interaction
          poetry run make
      - name: Check for changes
        id: check_changes
        run: |
          git diff-index --quiet HEAD || echo "changes_detected=true" >> $GITHUB_ENV
      - name: Commit files
        if: env.changes_detected == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "🚀 Automatically rebuilt derived files" -a
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        if: env.changes_detected == 'true'
        with:
          commit-message: Update KG-Registry metadata
          title: 'Update KG-Registry metadata'
          body: |
            Recreates all KG-Registry metadata.
