name: Update Registry Files

on:
  push:
    branches: [ main ]
    paths:
      - 'registry/**/*.yml'
      - 'registry/kgs.yml'
      - 'resource/**/*.md'
  workflow_dispatch:

jobs:
  update-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          
      - name: Update registry files
        run: |
          make all
          
      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add registry/kgs.jsonld registry/kgs.yml registry/kg_registry.duckdb registry/parquet/*.parquet registry/parquet-downloads.html
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update registry files" && git push)
